version: 0.1.0

name: A stack to deploy Github App to AWS Lambda
description: A stack to deploy Github app to AWS Lambda

branding:
  icon: "cloud"
  color: "red"

inputs:
  - name: AWS_ACCESS_KEY_ID
    description: Enter your AWS Key ID. This will be stored as a secret
    is-secret: true
    required: true

  - name: AWS_SECRET_ACCESS_KEY
    description: Enter your AWS Secret Access key. This will be stored as a secret
    is-secret: true
    required: true

  - name: SERVERLESS_ACCESS_KEY
    description: Enter the serverless Access Key. This will be stored as a secret
    is-secret: true
    required: true

configs:
  repo-metadata:
    parameters:
      description: "Node JS Application on Lambda"
      secrets:
        - name: AWS_SECRET_ACCESS_KEY
          value: ${{inputs.AWS_SECRET_ACCESS_KEY}}
        - name: AWS_SECRET_ACCESS_KEY
          value: ${{inputs.AWS_SECRET_ACCESS_KEY}}
        - name: SERVERLESS_ACCESS_KEY
          value: ${{inputs.SERVERLESS_ACCESS_KEY}}

      topics:
        - nodejs
        - aws
        - serverless
        - lambda
        - github-app
        - probot

  branches:
    - name: main
      parameters:
        allow-force-pushes: false
        allow-deletions: false

init:
  uses: "stack-init.yml"
